### PR TITLE
Implement empty chunk cache reset (DM-4383)

### PR DESCRIPTION
**Pull request by andy-slac**
Adding special SQL syntax for czar to reset empty chunk cache
(`FLUSH QSERV_CHUNKS_CACHE [FOR database]`). Wmgr also gets
a special method to reset chunks cache which uses above SQL.

### CODE REVIEW

**Comment by fritzm** [comment]
Sorry to come in to this discussion to so late.  It makes me a little uncomfortable to extend the SQL grammar for this.  What about just using stored-procedure "CALL" syntax instead on a magic procedure name for this instead of extending "FLUSH"?  Would that be better or worse?

**Comment by andy-slac** [comment]
I can't really say if it's better or worse. It may depend on what we plan to do with `CALL` in general (how do we handle it in proxy/Lua). My general idea is that we'll need to extend (or abuse/repurpose) some of the SQL syntax anyways (like `SHOW PROCESSLIST`) so we can't avoid introducing qserv-specific syntax. This new FLUSH syntax makes it very clear that it's Qserv extension, besides this is sort of internal command that end users are not supposed to even know, we can change it at any time to different syntax and not worry about compatibility. Still I'd be happy to change it to `CALL QSERV_FLUSH_CHUNKS_CACHE('db')` instead if people think it's a better way to extend qserv SQL interface.

**Comment by ktlim** [comment]
It does seem common for other databases to extend SQL syntax by both adding new syntax to existing verbs (like this) and adding new verbs.  Would it make it easier on the parser to just add a "QSERV" verb for all of our extensions that need to be at that level?

**Comment by andy-slac** [comment]
I guess it's mostly an issue of how user-friendly we want it to be (for user-facing queries). Do we want something like `QSERV SELECT ASYNC ...` instead of just `SELECT ASYNC ...`? I think latter is less surprising while still fits the pattern of SQL extensions supported by mysql. From the parser point of view it's certainly easier to have clear identifying token, but I don't think it's a good argument. I'd prefer to have syntax that fits well into existing language structure and has fewer surprises.
And QSERV is not a verb :) Not until we make it as popular as Google so people start saying "I qserved that" :tada:

**Comment by ktlim** [comment]
Definitely not "QSERV SELECT ASYNC" (although at first glance I would kind of prefer that asynchronicity be a property of the connection rather than the query).  As I said: "that need to be at that level" -- i.e. new top-level commands.

**Pull request merged**
